import { VideoData } from 'models/video';

const mockVideos: Array<VideoData> = [
    {
        id: '1',
        name: 'video 1',
        preview: 'https://i.ytimg.com/vi/xfcrXWIeImY/hqdefault.jpg',
        duration: new Date(),
        link: 'link',
    },
    {
        id: '2',
        name: 'video 2',
        preview: 'https://i.ytimg.com/vi/s3ZWHqjOtw8/hqdefault.jpg',
        duration: new Date(),
        link: 'link',
    },
    {
        id: '3',
        name: 'video 3',
        preview: 'https://i.ytimg.com/vi/TJX5yEQc3pk/hqdefault.jpg',
        duration: new Date(),
        link: 'link',
    },
    {
        id: '4',
        name: 'video 4',
        preview: 'https://i.ytimg.com/vi/xXz8aznZL2A/hqdefault.jpg',
        duration: new Date(),
        link: 'link',
    },
    {
        id: '5',
        name: 'video 5',
        preview: 'https://i.ytimg.com/vi/21Z4RIOFhMA/hqdefault.jpg',
        duration: new Date(),
        link: 'link',
    },
    {
        id: '6',
        name: 'video 6',
        preview: 'https://i.ytimg.com/vi/xMNGcdKoxb8/hqdefault.jpg',
        duration: new Date(),
        link: 'link',
    },
    {
        id: '7',
        name: 'video 7',
        preview: 'https://i.ytimg.com/vi/5NQizrXHYPc/hqdefault.jpg',
        duration: new Date(),
        link: 'link',
    },
    {
        id: '8',
        name: 'video 8',
        preview: 'https://i.ytimg.com/vi/H0LxBRYZs5o/hqdefault.jpg',
        duration: new Date(),
        link: 'link',
    },
    {
        id: '9',
        name: 'video 9',
        preview: 'https://i.ytimg.com/vi/V-AFfwQmrj0/hqdefault.jpg',
        duration: new Date(),
        link: 'link',
    },
    {
        id: '11',
        name: 'video 11',
        preview: 'https://i.ytimg.com/vi/xfcrXWIeImY/hqdefault.jpg',
        duration: new Date(),
        link: 'link',
    },
    {
        id: '12',
        name: 'video 12',
        preview: 'https://i.ytimg.com/vi/s3ZWHqjOtw8/hqdefault.jpg',
        duration: new Date(),
        link: 'link',
    },
    {
        id: '13',
        name: 'video 13',
        preview: 'https://i.ytimg.com/vi/TJX5yEQc3pk/hqdefault.jpg',
        duration: new Date(),
        link: 'link',
    },
    {
        id: '14',
        name: 'video 14',
        preview: 'https://i.ytimg.com/vi/xXz8aznZL2A/hqdefault.jpg',
        duration: new Date(),
        link: 'link',
    },
    {
        id: '15',
        name: 'video 15',
        preview: 'https://i.ytimg.com/vi/21Z4RIOFhMA/hqdefault.jpg',
        duration: new Date(),
        link: 'link',
    },
    {
        id: '16',
        name: 'video 16',
        preview: 'https://i.ytimg.com/vi/xMNGcdKoxb8/hqdefault.jpg',
        duration: new Date(),
        link: 'link',
    },
    {
        id: '17',
        name: 'video 17',
        preview: 'https://i.ytimg.com/vi/5NQizrXHYPc/hqdefault.jpg',
        duration: new Date(),
        link: 'link',
    },
    {
        id: '18',
        name: 'video 18',
        preview: 'https://i.ytimg.com/vi/H0LxBRYZs5o/hqdefault.jpg',
        duration: new Date(),
        link: 'link',
    },
    {
        id: '19',
        name: 'video 19',
        preview: 'https://i.ytimg.com/vi/V-AFfwQmrj0/hqdefault.jpg',
        duration: new Date(),
        link: 'link',
    },
];

export { mockVideos };